server:
  servlet:
    context-path: /v1/user-registration-api
spring:
  profiles:
    active: local
---
spring:
  profiles: local, it
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    sql-script-encoding: utf-8
    url: "jdbc:h2:mem:testdb"
---