DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE CATEGORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE PRODUCT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(20) UNIQUE NOT NULL,
    CATEGORY_ID BIGINT NOT NULL
);

ALTER TABLE PRODUCT ADD FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID);